import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";
import { AppProvider } from "./ContextApi";

const inter = Inter({ subsets: ["latin"] });

const poppins=Poppins({
  subsets:["latin"],
  variable:"--font-poppins",
  weight:["100","200","300","400","500","600","700","800","900"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet"/>
                                                    
           <ClerkProvider>
      <body className={ poppins.className }>
        <AppProvider>
        {children}
        </AppProvider>
        
        </body>
      
      </ClerkProvider>
     
      
    </html>
  );
}
 